version: '3'

services:
  test:
    image: ${USER}/${DIST-ubuntu}-${TAG-latest}-build
    depends_on:
      - mongodb
      - build
    environment:
      DB_URI: mongodb://mongodb/nextepc
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    hostname: nextepc-test
    command: /bin/bash -c "/root/setup.sh; sed 's|localhost|mongodb|' /usr/local/etc/nextepc/nextepc.conf > /tmp/nextepc.conf; mv -f /tmp/nextepc.conf /usr/local/etc/nextepc/; cd nextepc; ./test/testepc"
